Task/status bar notification
codota/tabnine-vscode pull request #222
Opened 2020-11-19 10:00 UTC by dimacodota

2020-11-19 16:26 UTC, dimacodota commented
nee to add test

2020-11-19 16:49 UTC, boaz-codota requested changes

2020-11-19 16:49 UTC, boaz-codota commented on src/extension.ts
> +import pollMessages, { dispose } from "./statusBarMessages/pollStatusBarMessages";
It is called a `status bar` so why call the thing `message` and not `status`? It is a bar of statuses...

2020-11-19 16:49 UTC, boaz-codota commented on src/extension.ts
> +  dispose();
Give it a more meaningful name, such as `disposeStatus`

2020-11-19 16:49 UTC, boaz-codota commented on src/notifications/pollNotifications.ts
> +    });
I'd love to know what that does

2020-11-19 16:49 UTC, boaz-codota commented on src/consts.ts
> +  process.env.BINARY_STATUS_BAR_POLLING_INTERVAL || 3600000
prefer multiplications for readability: `3600000` -> `60 * 60 * 1_000`

2020-11-19 16:49 UTC, boaz-codota commented on src/consts.ts
> +  process.env.STATUS_BAR_NOTIFICATION_PERIOD ||  60000 * 2
`60000 * 2` -> `2 * 60 * 1_000`

2020-11-19 16:49 UTC, boaz-codota commented on src/statusBar.ts
> +  statusBar.text = `${ATTRIBUTION_BRAND}${BRAND_NAME} : ${message}`;
there should be no space between `${BRAND_NAME}` and `:`

2020-11-19 16:49 UTC, boaz-codota commented on src/statusBarMessages/pollStatusBarMessages.ts
> +}
file is over 100 lines - split it

2020-11-19 16:49 UTC, boaz-codota commented on src/binary/requests/statusBar.ts
> +  OPEN_LP = 1,
I did a mistake when I did this thing in the notifications, and we don't need to repeat it. The binary is opening the LP so this air conditioning placement is redundant and will bite us in the future.

2020-11-19 16:49 UTC, boaz-codota commented on src/binary/requests/statusBar.ts
> +  OPEN_LP = 1,
In the minimum, just omit the OPEN_LP option so it will be clear that nothing is done

2020-11-22 08:16 UTC, boaz-codota approved these changes
🚀

2020-11-22 08:18 UTC, merged